name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: prepare system
      run: |
        sudo bash 0_setup.sh

    - name: compile singularity
      run: |
        sudo bash 1_build.sh

    - name: run singularity
      run: |
        singularity run docker://gcc:12.1 gcc --version
      