name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: prepare system
      run: |
        sudo bash 0_setup.sh

    - name: compile singularity
      run: |
        sudo bash 1_build.sh

    - name: run singularity
      run: |
        singularity run docker://alpine cat /etc/os-release
  
  build_tar:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: prepare system
      run: |
        sudo bash 0_setup.sh

    - name: build, package
      run: |
        id
        bash build.sh
        ls -lah
    
    - name: test run
      run: |
        tar xvf sing_deploy.tar.gz
        export PATH=$PWD/sing_deploy/bin:${PATH}
        singularity config global --set "mksquashfs path" $PWD/sing_deploy/bin/
        singularity run docker://alpine cat /etc/os-release

        

