name: ci

on: push

env:
  sin_version: "v3.8.4"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: prepare system
      run: |
        sudo bash 0_setup.sh

    - name: compile singularity
      run: |
        sudo bash 1_build.sh

    - name: run singularity
      run: |
        singularity run docker://alpine cat /etc/os-release
  
  build_tar:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: prepare system
      run: |
        sudo bash 0_setup.sh

    - name: build, package
      run: |
        export sin_version=${{ env.sin_version }}
        bash build.sh
    
    - name: test run
      run: |
        tar xf sing_deploy.tar.gz
        export PATH=$PWD/sing_deploy/bin:${PATH}
        singularity config global --set "mksquashfs path" $PWD/sing_deploy/bin/
        singularity run docker://alpine cat /etc/os-release

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.sin_version }}"
        prerelease: false
        title: "Singularity non-root deployment"
        files: |
          sing_deploy.tar.gz

        